# Scientific Computing: Arrays as Physical Data
Why Arrays Matter

Real materials problems involve many values:

atom positions<br>
temperatures<br>
stresses<br>
compositions<br>
grain sizes<br>

Single variables are insufficient.

In [2]:
import numpy as np

In [ ]:
# 1D arrays
temps = np.array([300, 320, 340, 360])
print(temps)

#This may represent temperature over time.

[300 320 340 360]


In [ ]:
# vectorized operations
temps_c = np.array([0,25,100])
temps_k = temps_c + 273.15
print(temps_k)

# Used for unit conversion.

[273.15 298.15 373.15]


In [ ]:
# 2D Arrays
A = np.array([
    [1,2],
    [3,4]
])
print(A)
#Used for matrices, coordinate tables.

[[1 2]
 [3 4]]


In [ ]:
# Shape

print(A.shape)

#Returns rows and columns.

(2, 2)


# Session 1 Exercises
Create array [1,2,3,4,5]<br>
Multiply by 10<br>
Convert Celsius [20,50,80] to Kelvin<br>
Create 2×2 zero matrix<br>